# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  habitsdevapi:
    image: habitsdevapi
    build:
      context: .
      dockerfile: src/HabitsDev.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
